---
- name: Configure Dev Web Server
  hosts: dev_webserver
  force_handlers: yes
  roles:
    - apache.developer_configs

  pre_tasks:
    - name: pre_task for selinux
      block:
        - name: add include_role
          include_role:
            name: redhat.rhel_system_roles.selinux

      rescue:
        - name: handle general failure
          ansible.builtin.fail:
            msg: "SELinux role failed"
          when: not selinux_reboot_required

        - name: Restart managed hosts
          ansible.builtin.reboot:
            msg: "Ansible rebooting system for updates."


        - name: Reapply SELinux role to complete changes
          include_role:
            name: redhat.rhel_system_roles.selinux
